-- ═══════════════════════════════════════════════════════════════════════════
-- VIAGENS — PASSAGENS E HOSPEDAGENS (2026-09-25). Idempotente.
--
-- Para diretores, funcionários e convidados de eventos cuja passagem ou
-- hospedagem o sindicato contrata e paga. Decisões do Bruno (25/09):
--  1. Uma solicitação é a VIAGEM inteira — ida, volta e hotel juntos, que é
--     como a agência cota. Cada trecho ou estadia é um item.
--  2. Sem aprovação prévia: a alçada das compras já controla o pagamento.
--  3. Convidado não tem conta — quem pede por ele é a gestão de Viagens.
--  4. As contas contábeis reusam a configuração das diárias (fase 3).
--
-- O módulo se chama "Viagens" porque /painel/hospedagem já é o convênio de
-- hotéis dos filiados.
--
-- Horários ficam em DATA + HORA separadas (date/time, sem fuso): "saída até as
-- 10h" é hora local do lugar, e datetime-local já corrompeu hora aqui antes.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 0. Permissão ────────────────────────────────────────────────────────────
-- `diretoria_passagens` era chave herdada do Bubble, sem tela. Quem a tinha
-- passa a ter `viagens_gestao`. `atualizarAcesso` grava todas as chaves do
-- catálogo, então a coluna precisa existir ANTES do deploy.

alter table public.permissoes
  add column if not exists viagens_gestao boolean;

comment on column public.permissoes.viagens_gestao is
  'Atender as solicitações de passagem e hospedagem, lançar em nome de outra pessoa e faturar.';

update public.permissoes
set viagens_gestao = true
where diretoria_passagens = true
  and viagens_gestao is null;

insert into public.perfil_permissoes (perfil_id, emp_proprietaria_id, chave)
select perfil_id, emp_proprietaria_id, 'viagens_gestao'
from public.perfil_permissoes
where chave = 'diretoria_passagens'
on conflict (perfil_id, chave) do nothing;

-- ── 1. Solicitação (a viagem) ───────────────────────────────────────────────

create table if not exists public.viagens_solicitacoes (
  id uuid primary key default gen_random_uuid(),
  emp_proprietaria_id uuid references public.empresa (id),
  numero bigint generated by default as identity,

  -- Quem viaja. Diretor e funcionário por usuario; convidado pelos campos
  -- próprios (não tem conta).
  beneficiario_tipo text not null
    check (beneficiario_tipo in ('funcionario', 'diretor', 'convidado')),
  beneficiario_usuario_id uuid references public.usuarios (id),
  convidado_nome text,
  convidado_cpf text,
  convidado_nascimento date,
  convidado_email text,
  convidado_telefone text,

  -- Contexto
  solicitante_id uuid references public.usuarios (id),
  departamento_id uuid references public.empresa_departamentos (id),
  evento_id uuid references public.eventos (id) on delete set null,
  evento_inscricao_id uuid references public.eventos_inscricoes (id) on delete set null,
  motivo text not null,

  -- Andamento
  situacao text not null default 'solicitada'
    check (situacao in ('solicitada', 'em_atendimento', 'atendida', 'cancelada', 'recusada')),
  motivo_situacao text,
  atendido_por uuid references public.usuarios (id),
  atendido_em timestamptz,
  encerrado_em timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz,

  constraint viagens_solicitacoes_beneficiario_check check (
    (beneficiario_tipo = 'convidado' and convidado_nome is not null)
    or (beneficiario_tipo <> 'convidado' and beneficiario_usuario_id is not null)
  )
);

create index if not exists idx_viagens_solic_emp_criacao
  on public.viagens_solicitacoes (emp_proprietaria_id, created_at desc);
create index if not exists idx_viagens_solic_beneficiario
  on public.viagens_solicitacoes (beneficiario_usuario_id);
create index if not exists idx_viagens_solic_solicitante
  on public.viagens_solicitacoes (solicitante_id);
create index if not exists idx_viagens_solic_situacao
  on public.viagens_solicitacoes (emp_proprietaria_id, situacao);
create index if not exists idx_viagens_solic_evento
  on public.viagens_solicitacoes (evento_id);

comment on table public.viagens_solicitacoes is
  'Pedido de viagem (passagens e/ou hospedagens) para diretor, funcionário ou convidado. Os trechos e estadias ficam em viagens_itens.';
comment on column public.viagens_solicitacoes.solicitante_id is
  'Quem lançou. Igual ao beneficiário quando a pessoa pediu para si; a gestão lança por diretor sem conta e por convidado.';
comment on column public.viagens_solicitacoes.departamento_id is
  'Departamento que banca a viagem — dá a conta contábil (mesmo de-para das diárias).';

-- ── 2. Itens: trechos de passagem e estadias ────────────────────────────────

create table if not exists public.viagens_itens (
  id uuid primary key default gen_random_uuid(),
  emp_proprietaria_id uuid references public.empresa (id),
  solicitacao_id uuid not null
    references public.viagens_solicitacoes (id) on delete cascade,
  tipo text not null check (tipo in ('passagem', 'hospedagem')),
  ordem integer not null default 0,

  -- Passagem
  modal text check (modal in ('aerea', 'rodoviaria')),
  origem text,
  destino text,
  data_viagem date,
  saida_criterio text check (saida_criterio in ('ate', 'depois')),
  saida_hora time,
  chegada_criterio text check (chegada_criterio in ('ate', 'depois')),
  chegada_hora time,
  bagagem_extra boolean not null default false,
  bagagem_descricao text,

  -- Hospedagem
  cidade text,
  checkin date,
  checkout date,

  -- Dos dois
  necessidades_especiais text,
  observacoes text,

  -- Atendimento (preenchido pela gestão na fase 2)
  fornecedor_id uuid references public.empresa (id),
  localizador text,
  reserva_descricao text,
  valor numeric check (valor is null or valor >= 0),
  -- Bilhete ou voucher no bucket `compras`, em viagens/<solicitacao>/<item>.pdf
  voucher text,

  created_at timestamptz not null default now(),
  updated_at timestamptz,

  constraint viagens_itens_passagem_check check (
    tipo <> 'passagem'
    or (modal is not null and origem is not null and destino is not null and data_viagem is not null)
  ),
  constraint viagens_itens_hospedagem_check check (
    tipo <> 'hospedagem'
    or (cidade is not null and checkin is not null and checkout is not null and checkout > checkin)
  )
);

create index if not exists idx_viagens_itens_solicitacao
  on public.viagens_itens (solicitacao_id, ordem);
create index if not exists idx_viagens_itens_tipo
  on public.viagens_itens (emp_proprietaria_id, tipo);

comment on table public.viagens_itens is
  'Cada trecho de passagem (aérea ou rodoviária) ou estadia de hospedagem de uma viagem.';
comment on column public.viagens_itens.saida_criterio is
  'ate = sair no máximo até saida_hora; depois = sair a partir de saida_hora.';

-- ── 3. RLS por tenant (padrão da casa) ──────────────────────────────────────

do $$
declare t text;
begin
  foreach t in array array['viagens_solicitacoes', 'viagens_itens'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists tenant_isolation on %I', t);
    execute format(
      'create policy tenant_isolation on %I for all to authenticated
         using (emp_proprietaria_id = (auth.jwt() ->> ''tenant_id'')::uuid)
         with check (emp_proprietaria_id = (auth.jwt() ->> ''tenant_id'')::uuid)', t);
    execute format('grant select, insert, update, delete on %I to authenticated', t);
    execute format('drop trigger if exists set_emp_from_jwt on %I', t);
    execute format('create trigger set_emp_from_jwt before insert on %I for each row execute function public.set_emp_from_jwt()', t);
  end loop;
end $$;

notify pgrst, 'reload schema';
