import {
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Car,
  ClipboardCheck,
  FileSignature,
  FileText,
  FolderKanban,
  Gavel,
  HeartPulse,
  Hotel,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Mail,
  Megaphone,
  Newspaper,
  Receipt,
  Rss,
  Scale,
  ScrollText,
  Settings,
  ShoppingCart,
  TriangleAlert,
  Users,
  Vote,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react"

/** Mapa nome → componente, para que a config de módulos (server) fique serializável. */
export const ICONES_MODULOS: Record<string, LucideIcon> = {
  LayoutDashboard,
  Boxes,
  Building2,
  Users,
  Landmark,
  Receipt,
  Wallet,
  BriefcaseBusiness,
  ShoppingCart,
  Car,
  ClipboardCheck,
  Hotel,
  Scale,
  HeartPulse,
  Vote,
  CalendarDays,
  FileText,
  FileSignature,
  FolderKanban,
  Gavel,
  ListChecks,
  Mail,
  Megaphone,
  Newspaper,
  Rss,
  ScrollText,
  TriangleAlert,
  Wrench,
  Settings,
}
